language: go

go:
  - 1.12.x

script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
