delay=500

[[watch]]
name = "linter"
paths = ["vendor/github.com"]
commands = ["sleep 1", "sleep 1", "ls /sfsdfsdf"]

[[watch]]
name = "tests"
paths = ["."]
ignorePrefixes = ["vendor"]
commands = ["sleep 5"]
